import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Tadabbur",
  description:
    "Privacy policy for the Tadabbur app — a daily Quranic contemplation app.",
};

export default function PrivacyPage() {
  return (
    <main className="section-padding">
      <div className="mx-auto max-w-3xl px-6 pt-24">
        {/* Back link */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-text-secondary hover:text-gold transition-colors text-sm mb-12"
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="m12 19-7-7 7-7" />
            <path d="M19 12H5" />
          </svg>
          Back to home
        </Link>

        {/* Header */}
        <header className="mb-16">
          <span className="text-gold text-sm font-semibold uppercase tracking-widest mb-4 block">
            Legal
          </span>
          <h1 className="text-4xl md:text-5xl font-bold text-text-primary mb-4">
            Privacy Policy
          </h1>
          <p className="text-text-muted text-sm">
            Last updated: May 4, 2026
          </p>
        </header>

        {/* Content */}
        <article className="prose prose-invert max-w-none space-y-10 text-text-secondary leading-relaxed">
          <section>
            <p className="text-lg">
              Tadabbur (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;)
              is committed to protecting your privacy. This Privacy Policy
              explains how we collect, use, and safeguard information when you
              use the Tadabbur mobile application.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              1. Information We Collect
            </h2>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Account Information
            </h3>
            <p>
              When you sign in with Google, Apple, or Quran Foundation
              (quran.com), we receive your name, email address, and profile
              image as provided by the identity provider. If you sign in with
              Apple and choose &ldquo;Hide My Email,&rdquo; we receive only
              the relayed email address generated by Apple. You may also use
              Tadabbur as a guest without creating an account, in which case
              no account information is collected.
            </p>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Reflections, Bookmarks, and Streaks
            </h3>
            <p>
              Reflections you write, verses you bookmark, and your streak
              progress are stored locally on your device. If you are signed
              in, they are also synced to our secure cloud (Google Firestore)
              so you can access them across devices. If you are signed in
              with Quran Foundation, they are additionally mirrored to your
              Quran Foundation account so they appear on quran.com.
            </p>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Public Sharing (Opt-In Per Reflection)
            </h3>
            <p>
              When you write a tier-3 reflection (eighty characters or
              longer) while signed in with Quran Foundation, the app displays
              an opt-in toggle to share that specific reflection to{" "}
              <a
                href="https://quran.com/reflect"
                className="text-gold hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Quran Reflect
              </a>
              , a public reflection feed operated by the Quran Foundation.
              Sharing is opt-in per reflection; the default is private.
              Once shared, the reflection &mdash; along with your Quran
              Foundation profile name &mdash; becomes visible to other Quran
              Reflect users. Subsequent moderation, takedown, and visibility
              on Quran Reflect are governed by the Quran Foundation&rsquo;s
              privacy policy and terms of service:{" "}
              <a
                href="https://quran.com/privacy"
                className="text-gold hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                quran.com/privacy
              </a>
              .
            </p>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Feedback You Submit
            </h3>
            <p>
              When you submit feedback through Settings &rarr; Send feedback,
              your message is sent by email to our team along with your
              account identity (display name, email address, sign-in method,
              and Quran Foundation username if applicable) so we can follow
              up. Feedback content is not used for analytics and is not
              shared with third parties.
            </p>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Analytics and Crash Reports
            </h3>
            <p>
              We use Firebase Analytics and Firebase Crashlytics to understand
              how the app is used and to diagnose crashes. This includes device
              type, operating system version, app version, language, and
              anonymized usage events (e.g. &ldquo;ayah completed&rdquo;,
              &ldquo;reflection added&rdquo;). The content of your reflections
              is never sent to analytics.
            </p>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              Preferences
            </h3>
            <p>
              Your language, reciter, font size, and notification time are
              stored locally on your device.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              2. How We Use Your Information
            </h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>To deliver daily ayah content, translations, and audio</li>
              <li>To save and sync your reflections, bookmarks, and progress</li>
              <li>To send daily reflection reminders (with your permission)</li>
              <li>To improve the app through anonymized analytics</li>
              <li>To diagnose and fix crashes</li>
              <li>To respond to feedback you submit</li>
            </ul>
            <p className="mt-4">
              We do not sell, rent, or share your personal information with
              third parties for marketing purposes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              3. Notifications
            </h2>
            <p>
              Daily ayah reminders are scheduled and delivered locally by
              your device. We do not send push notifications and do not use
              Apple Push Notification Service (APNs) or Firebase Cloud
              Messaging.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              4. Third-Party Services
            </h2>
            <p>Tadabbur uses the following trusted third-party services:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>
                <strong className="text-text-primary">
                  Google Firebase
                </strong>{" "}
                &mdash; authentication, cloud storage, analytics, crash
                reporting (
                <a
                  href="https://policies.google.com/privacy"
                  className="text-gold hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Google Privacy Policy
                </a>
                )
              </li>
              <li>
                <strong className="text-text-primary">
                  Quran Foundation
                </strong>{" "}
                &mdash; Quran text, translations, tafsir, audio, and the
                public Quran Reflect feed (
                <a
                  href="https://quran.com/privacy"
                  className="text-gold hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Quran Foundation Privacy Policy
                </a>
                )
              </li>
              <li>
                <strong className="text-text-primary">
                  Islamic Network CDN
                </strong>{" "}
                &mdash; audio recitation files
              </li>
              <li>
                <strong className="text-text-primary">Google Sign-In</strong>{" "}
                and{" "}
                <strong className="text-text-primary">
                  Sign in with Apple
                </strong>{" "}
                &mdash; optional authentication (
                <a
                  href="https://www.apple.com/legal/privacy/"
                  className="text-gold hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Apple Privacy Policy
                </a>
                )
              </li>
            </ul>
            <p className="mt-4">
              Each service has its own privacy policy. We encourage you to
              review them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              5. Data Security
            </h2>
            <p>
              Authentication tokens are encrypted and stored securely on your
              device using platform-native secure storage (Android
              EncryptedSharedPreferences, iOS Keychain). All network
              communication is encrypted via HTTPS. Cloud data is stored in
              Google Firestore with access controls that restrict reads and
              writes to the authenticated user only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              6. Offline Use
            </h2>
            <p>
              Tadabbur is designed to work offline. Your reflections, bookmarks,
              and progress are always saved locally first, then synced to the
              cloud when you reconnect. You can use the entire app as a guest
              without any data leaving your device.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              7. Your Rights
            </h2>
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Access the personal information we hold about you</li>
              <li>Delete your account and all associated data</li>
              <li>Opt out of analytics and crash reporting through your device settings</li>
              <li>Export your reflections as text</li>
            </ul>

            <h3 className="text-lg font-semibold text-text-primary mt-6 mb-2">
              How to delete your account
            </h3>
            <p>
              In the app: open Settings &rarr; Account &rarr; Delete account.
              This permanently removes your synced reflections, bookmarks,
              streaks, and profile data from our servers within thirty days.
              Local data on the device is removed immediately upon account
              deletion or app uninstall. Reflections you previously chose to
              publish to Quran Reflect remain governed by the Quran
              Foundation&rsquo;s policies; contact Quran Foundation directly
              to request their removal.
            </p>
            <p className="mt-4">
              Alternatively, see our{" "}
              <Link
                href="/delete-account"
                className="text-gold hover:underline"
              >
                account deletion page
              </Link>
              {" "}or email{" "}
              <a
                href="mailto:thetadabburapp@gmail.com"
                className="text-gold hover:underline"
              >
                thetadabburapp@gmail.com
              </a>
              {" "}from your account email with the subject &ldquo;Account
              deletion request&rdquo; and we will process it within seven
              days.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              8. Children&rsquo;s Privacy
            </h2>
            <p>
              Tadabbur is suitable for users of all ages and does not
              knowingly collect personal information from children under 13
              beyond what is necessary to provide the service. Parents and
              guardians who believe we may have collected information about a
              child should contact us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              9. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will
              notify you of significant changes through the app or by updating
              the &ldquo;Last updated&rdquo; date above.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-text-primary mb-4">
              10. Contact Us
            </h2>
            <p>
              If you have questions about this Privacy Policy or your data,
              please contact us at:
            </p>
            <p className="mt-4">
              <a
                href="mailto:thetadabburapp@gmail.com"
                className="text-gold hover:underline"
              >
                thetadabburapp@gmail.com
              </a>
            </p>
          </section>
        </article>

        {/* Footer link */}
        <div className="geometric-divider my-16" />
        <div className="text-center">
          <Link
            href="/"
            className="text-text-secondary hover:text-gold transition-colors text-sm"
          >
            &larr; Return to Tadabbur
          </Link>
        </div>
      </div>
    </main>
  );
}
